### ISSUE TITLE
Wrong getItem() method visibility

### ISSUE THREAD

**Issue by alexgutnik** [dmstr/yii2-pages-module#19]
I use DbManager for RBAC and get next error:

```
[error][yii\base\UnknownMethodException] exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\rbac\DbManager::getItem()'
Stack trace:
#0 project_path\vendor\dmstr\yii2-db\db\traits\ActiveRecordAccessTrait.php(195): yii\base\Component->__call('getItem', Array)
#1 project_path\vendor\dmstr\yii2-db\db\traits\ActiveRecordAccessTrait.php(195): yii\rbac\DbManager->getItem('admin')
#2 project_path\vendor\dmstr\yii2-db\db\traits\ActiveRecordAccessTrait.php(77): dmstr\modules\pages\models\BaseTree::getUsersAuthItems()
#3 project_path\vendor\yiisoft\yii2\db\ActiveRecord.php(172): dmstr\modules\pages\models\BaseTree::find()
#4 project_path\vendor\yiisoft\yii2\db\BaseActiveRecord.php(107): yii\db\ActiveRecord::findByCondition(Array)
#5 project_path\vendor\dmstr\yii2-pages-module\Module.php(100): yii\db\BaseActiveRecord::findOne(Array)
#6 project_path\vendor\dmstr\yii2-pages-module\controllers\DefaultController.php(31): dmstr\modules\pages\Module->getLocalizedRootNode()
#7 [internal function]: dmstr\modules\pages\controllers\DefaultController->actionIndex()
#8 project_path\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#9 project_path\vendor\yiisoft\yii2\base\Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#10 project_path\vendor\yiisoft\yii2\base\Module.php(523): yii\base\Controller->runAction('', Array)
#11 project_path\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('pages', Array)
#12 project_path\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request))
#13 project_path\backend\web\index.php(17): yii\base\Application->run()
```

That's because DbManager::getItem() method is protected. But getItem() from PhpManager is public. As I understand, yii2-pages-module uses only DbManager but code is not compatible with one? Or how can I add rules to PhpManager automatically?

P.S.
ext v. 0.21.8
yii2 v. 2.0.12

**Comment by schmunk42** [comment]
Looks more related to `yii2-db` https://github.com/dmstr/yii2-db/blob/master/db/traits/ActiveRecordAccessTrait.php#L195 to me.

We're not using PhpManager AFAIR in any project, I basically understand the issue from looking at the code, but I can't reproduce it atm.

Can you provide code to reproduce the problem?
